### ISSUE TITLE
Properties not matching JS symbols

### ISSUE THREAD

**Issue by lngns** [SharpKit/SharpKit-SDK#12]
Some properties in the SDK are defined with getters and setters but because the compiler generates special symbols for them, the compiled code uses non-existing symbols.

For example `SharpKit.NodeJs.cluster.Utils.isMaster` is defined as a property and using it like this:
```csharp
if(Cluster.isMaster) { /*...*/ }
```
Will generate this JavaScript code:
```js
if(Cluster.get_isMaster()){ /*...*/ }
```
Which will throw an error as `get_isMaster` is not defined in the NodeJS API.

Switching some of these properties to public readonly fields seems to do the job but the JsProperty attributes of the convenience ones prevents me from doing it on them.
Concerning these convenience properties, using functions like `require("cluster").on` works but they are not defined in the SDK.

**Comment by danelkhen** [comment]
Hi,

Try adding [JsProperty(Native=true)] on the isMaster property, this should treat it as native. You can also set it on the class level: [JsType(NativeProperties=true)], or [JsType(JsMode.Prototype)] which should set some other options that makes the compiler assume that these classes/interfaces are native and not .NET based.

**Comment by lngns** [comment]
Hi,

Using `[JsProperty(NativeField=true)]` on the properties is working but the two other options you talked about force the creation of the class in the compiled code, (at least on my computer).
It appears that `[JsType(JsMode.Json)]` at the class level achieves it though, but I think the name may be misleading.
Is there an alias for JsMode.Json like "JsMode.Native"?

**Comment by danelkhen** [comment]
Oh, right, please use this:
```
[JsType(JsMode.Prototype, Export = false)]
```
If you're writing your typings inside the same project that you compile using SharpKit, you need ```Export=false``` to tell SharpKit to *not* generate any code for the type. Otherwise, if you put all your typings in a separate project, you can build it as a regular dll, without adding the SharpKit build step to it, then you won't need ```Export=false```.

To answer your other question: ```JsMode.Native``` does not exist by that name but it's essentially ```JsMode.Prototype```, in retrospect your name is much better :-).

**Comment by lngns** [comment]
Hi,

Sorry for the late reply, I was working on something else these past days.
I copied the SDK in my project to have a quick access to it and some classes were missing the `Export=false` part. _(And I did not realize it)_
I'm not sure if this is intentional, and I did not read the whole codebase so there's probably only one missing it actually.
I know that `SharpKit.NodeJs.cluster.Utils` does not have it.

It also does not extend `SharpKit.NodeJs.IRequirable`.
It is not that big of an issue given that other classes don't as well and `require` returns a dynamic type, but `HttpPlugin` do, so I prefer asking if this is intentional or I'm just missing something again here.

**Comment by danelkhen** [comment]
If you're asking about Export=false, it's usually not needed since typings usually exist in a separate C# project, which does not need the SharpKit compilation step in its project file (<import> line in proj). So most typings libraries might not write it at all. So, without the compilation step, SharpKit will not compile / generate any code anyway.

**Comment by lngns** [comment]
It makes sense.
Thank you for your time.
